on:
  pull_request:
    types: [opened]

jobs:
  create-unit-test:
    runs-on: ubuntu-latest
    name: Create unit test
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35  
        with:
          separator: ','

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
        
      - name: Generate unit test 
        uses: ./.github/actions
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }} # Get the Github Token from repository secrets
          changed_files: ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Commit changes to branch
        run: |
          git config --global user.email "robot@gptest.com"
          git config --global user.name "GPTest Robot"
          git checkout -B gptest-${{ github.head_ref }}
          git add .
          git commit -m "GPTest unit test"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gptest-${{ github.head_ref }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gptest-${{ github.head_ref }}
          commit-message: "Update code"
          title: "[GPTest] Unit Test Creation"
          body: "Unit test for the modified functions of your ."
